# Generated by Django 4.2.7 on 2025-05-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='Qabul sanasi')),
                ('appointment_time', models.TimeField(verbose_name='Qabul vaqti')),
                ('status', models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('confirmed', 'Tasdiqlangan'), ('completed', 'Tugallangan'), ('cancelled', 'Bekor qilingan'), ('no_show', 'Kelmagan')], default='scheduled', max_length=20, verbose_name='Holati')),
                ('reason', models.TextField(blank=True, verbose_name='Murojaat sababi')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor', verbose_name='Shifokor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Qabulga yozilish',
                'verbose_name_plural': 'Qabulga yozilishlar',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
    ]
