# Generated by Django 4.2.7 on 2025-05-24 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Erkak'), ('F', 'Ayol')], max_length=1, null=True, verbose_name='Jinsi')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Qon guruhi')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='Favqulodda aloqa')),
                ('emergency_phone', models.CharField(blank=True, max_length=15, verbose_name='Favqulodda telefon')),
                ('medical_history', models.TextField(blank=True, verbose_name='Tibbiy tarix')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergiyalar')),
                ('current_medications', models.TextField(blank=True, verbose_name='Joriy dorilar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bemor',
                'verbose_name_plural': 'Bemorlar',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(verbose_name='Tashxis')),
                ('treatment', models.TextField(verbose_name='Davolash')),
                ('prescription', models.TextField(blank=True, verbose_name='Retsept')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='Shifokor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Tibbiy yozuv',
                'verbose_name_plural': 'Tibbiy yozuvlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
